server:
  port: 8084
spring:
  datasource:
    url: jdbc:mysql://mysqldb:3306/oauth2db?setUnicode=true&characterEncoding=utf8
    username: xiaodong
    password: time4@FUN
    driver-class-name: com.mysql.cj.jdbc.Driver
  #redis配置数据
#  redis:
#    hostName: xdredis
#    port: 6379
#    database: 0
#    password:
#    timeout: 5000
fsdemo:
  usercenter:
    userinfourl: http://fsdemo-usercenter:8081/usercenter/user?username={username}

debug: true