server:
  port: 8084
spring:
  datasource:
    url: jdbc:mysql://mysqldb:3306/oauth2db?setUnicode=true&characterEncoding=utf8
    username: xiaodong
    password: time4@FUN
    driver-class-name: com.mysql.cj.jdbc.Driver
debug: false